package com.logitrack.logitrack.service;

import com.logitrack.logitrack.dto.warehouse.WarehouseDTO;
import com.logitrack.logitrack.exception.BusinessException;
import com.logitrack.logitrack.exception.ConflictException;
import com.logitrack.logitrack.exception.ResourceNotFoundException;
import com.logitrack.logitrack.mapper.WarehouseMapper;
import com.logitrack.logitrack.model.Inventory;
import com.logitrack.logitrack.model.Product;
import com.logitrack.logitrack.model.User;
import com.logitrack.logitrack.model.enums.UserRole;
import com.logitrack.logitrack.model.Warehouse;
import com.logitrack.logitrack.repository.InventoryRepository;
import com.logitrack.logitrack.repository.SalesOrderRepository;
import com.logitrack.logitrack.repository.UserRepository;
import com.logitrack.logitrack.repository.WarehouseRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.logitrack.logitrack.model.enums.SalesOrderStatus;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class WarehouseService {

    private final WarehouseRepository warehouseRepository;
    private final UserRepository userRepository;
    private final WarehouseMapper warehouseMapper;
    private final InventoryRepository inventoryRepository;
    private final SalesOrderRepository salesOrderRepository;


    @Transactional
    public WarehouseDTO createWarehouse(WarehouseDTO warehouseDTO) {
        // Only check for duplicate code if one was provided
        if (warehouseDTO.getCode() != null && !warehouseDTO.getCode().isEmpty()) {
            warehouseRepository.findByCode(warehouseDTO.getCode()).ifPresent(w -> {
                throw new BusinessException("Warehouse code '" + warehouseDTO.getCode() + "' already exists");
            });
        }

        User manager = validateWarehouseManager(warehouseDTO.getWarehouseManagerId());

        Warehouse warehouse = warehouseMapper.toEntity(warehouseDTO);
        warehouse.setWarehouseManager(manager);
        warehouse.setActive(true);
        // Code will be auto-generated by @PrePersist if null

        Warehouse savedWarehouse = warehouseRepository.save(warehouse);
        return warehouseMapper.toDto(savedWarehouse);
    }

    @Transactional
    public WarehouseDTO updateWarehouse(Long id, WarehouseDTO warehouseDTO) {
        Warehouse existingWarehouse = warehouseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Warehouse not found with id: " + id));

        User manager = validateWarehouseManager(warehouseDTO.getWarehouseManagerId());

        existingWarehouse.setCode(warehouseDTO.getCode());
        existingWarehouse.setName(warehouseDTO.getName());
        existingWarehouse.setActive(warehouseDTO.isActive());
        existingWarehouse.setWarehouseManager(manager);

        Warehouse updatedWarehouse = warehouseRepository.save(existingWarehouse);
        return warehouseMapper.toDto(updatedWarehouse);
    }

    @Transactional
    public WarehouseDTO deactivateWarehouse(Long id) {
        Warehouse warehouse = warehouseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Warehouse not found with id: " + id));

        warehouse.setActive(false);
        Warehouse deactivatedWarehouse = warehouseRepository.save(warehouse);
        return warehouseMapper.toDto(deactivatedWarehouse);
    }

    @Transactional(readOnly = true)
    public WarehouseDTO getWarehouseById(Long id) {
        Warehouse warehouse = warehouseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Warehouse not found with id: " + id));
        // Eagerly load inventory to avoid LazyInitializationException
        warehouse.getInventory().size();
        return warehouseMapper.toDto(warehouse);
    }

    @Transactional(readOnly = true)
    public WarehouseDTO getWarehouseByCode(String code) {
        Warehouse warehouse = warehouseRepository.findByCode(code)
                .orElseThrow(() -> new ResourceNotFoundException("Warehouse not found with code: " + code));
        // Eagerly load inventory to avoid LazyInitializationException
        warehouse.getInventory().size();
        return warehouseMapper.toDto(warehouse);
    }




    @Transactional(readOnly = true)
    public List<WarehouseDTO> getAllWarehouses() {
        return warehouseRepository.findAll()
                .stream()
                .map(warehouseMapper::toDto)
                .toList();
    }

    private User validateWarehouseManager(Long managerId) {
        if (managerId == null) {
            throw new BusinessException("Warehouse Manager ID cannot be null");
        }

        User manager = userRepository.findById(managerId)
                .orElseThrow(() -> new ResourceNotFoundException("User (Manager) not found with id: " + managerId));

        if (manager.getRole() != UserRole.WAREHOUSE_MANAGER) {
            throw new BusinessException("User " + manager.getEmail() + " does not have the WAREHOUSE_MANAGER role");
        }

        return manager;
    }

    @Transactional
    public void deleteWarehouse(Long id) {
        // Vérifier si l'entrepôt existe
        Warehouse warehouse = warehouseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Warehouse not found with id: " + id));

        // Vérifier si l'entrepôt contient du stock physique (qtyOnHand > 0)
        Long stockCount = inventoryRepository.countByWarehouseIdAndQtyOnHandGreaterThan(id, 0);
        if (stockCount > 0) {
            throw new ConflictException("Cannot delete warehouse with id " + id + " because it contains " + stockCount + " product(s) with physical stock");
        }

        // Vérifier si l'entrepôt est associé à des commandes actives (CREATED ou RESERVED)
        boolean hasActiveOrders = salesOrderRepository.existsByWarehouseIdAndStatusIn(
                id,
                List.of(SalesOrderStatus.CREATED, SalesOrderStatus.RESERVED)
        );
        if (hasActiveOrders) {
            throw new ConflictException("Cannot delete warehouse with id " + id + " because it is associated with active sales orders (CREATED or RESERVED)");
        }

        // Supprimer l'entrepôt
        warehouseRepository.delete(warehouse);
    }

//    public List<Inventory> getInventoriesByWarehouseId(Long warehouseId) {
//        List<Inventory> WarehouseInventories = warehouseRepository.GetWarehouseInventoryByWarehouseId(warehouseId);
//
//        return WarehouseInventories;
//    }
}
